tabas/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :houses
  # get 'home/index'
  #faz o home/index ser a pagina default do app
  root 'home#index'
  
  #caminho para "houses"
  get 'home/houses'
end

tabas/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tabas/app/models/house.rb
class House < ApplicationRecord
    belongs_to :user
end

tabas/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

tabas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tabas/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def houses
  end
end

tabas/app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index,:show]
  # GET /houses or /houses.json
  def index
    @houses = House.all
  end

  # GET /houses/1 or /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    respond_to do |format|
      if @house.save
        format.html { redirect_to house_url(@house), notice: "House was successfully created." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to house_url(@house), notice: "House was successfully updated." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:name, :address, :prince, :rooms, :bathrooms, :picture_one, :picture_two, :picture_three, :user_id)
    end
end

tabas/app/helpers/application_helper.rb
module ApplicationHelper
end

tabas/app/helpers/home_helper.rb
module HomeHelper
end

tabas/app/helpers/houses_helper.rb
module HousesHelper
end

tabas/app/views/home/_header.html.erb
<header><!--inicio cabecalho--> 
      <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-branca">
        <div class="container">

         
            <%= link_to image_tag("tabas.svg", :alt => "tabas",style: 'height:30%;width:40%;'), root_path, class:"navbar-brand" %>
          

          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <i class="fas fa-bars text-black"></i>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto ">
              <li class="navbar-item separar">
                <%= link_to 'APARTMENTS', home_houses_path, class:"nav-link" %>
              </li>
              <li class="navbar-item separar">
                
                <%= link_to 'PROPERTY OWNER', new_user_session_path, class:"nav-link"%>
              </li>
              <li class="navbar-item separar">
                <%= link_to 'CORPORATE', new_user_session_path, class:"nav-link"%>
              </li>
              <li class="navbar-item separar">
              <a href="" class="nav-link">BLOG</a>
              </li>
              <li class="navbar-item separar">
                 <a class="nav-link"><%= image_tag("globe.png", :alt => "globe",style: 'height:auto;width:auto;') %>  </a>
                 
              </li>
              <li class="navbar-item separar">
                <a href="" class="nav-link">SUPPORT</a>
              </li>

            <% if user_signed_in?%>
                <li class="navbar-item separar">
                
                <%= link_to 'SIGN OUT', destroy_user_session_path,method: :delete, class:"nav-link"%>
                </li>

                <li class="navbar-item separar">
                
                <%= link_to 'EDIT PROFILE', edit_user_registration_path, class:"nav-link"%>
                 </li>

                 <li class="navbar-item separar">
                    <%= link_to 'NEW HOUSE', new_house_path, class:"nav-link"%>
                 </li>

            <% else %>
              <li class="navbar-item separar">
                
                <%= link_to 'SIGN UP', new_user_registration_path, class:"nav-link"%>
              </li>

              <li class="navbar-item separar">
                
                <%= link_to 'SIGN IN', new_user_session_path, class:"nav-link"%>
              </li>
            <% end %>
              
            </ul>
          </div>

        </div>
        
      </nav>
</header><!--fim cabecalho-->

tabas/app/views/home/houses.html.erb
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
       

        <div class="container">
        <%= image_tag("apartments_1.jpg", :alt => "design", class:"bd-placeholder-img capa-carro") %>
          <div class="carousel-caption">
            <h1>R. Fernando de Albuquerque, 86 - Consolação - CS003</h1>
            <p><a class="btn btn-lg btn-dark" href="#">info</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        

        <div class="container">
        <%= image_tag("apartments_2.jpg", :alt => "design", class:"bd-placeholder-img capa-carro") %>
          <div class="carousel-caption">
            <h1>R. Gararu, 140 - Vila Nova Conceição - N012</h1>
            <p><a class="btn btn-lg btn-dark" href="#">info</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        
        <div class="container">
          <%= image_tag("apartments_4.jpg", :alt => "design",class:"bd-placeholder-img capa-carro") %> 
          <div class="carousel-caption">
            <h1>R. Pedroso Alvarenga, 505 - Itaim Bibi - I113</h1>
            <p><a class="btn btn-lg btn-dark" href="#">info</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing mt-4">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        
        <%= image_tag("apartments_9.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle seg-carro") %>
        

        <h2>R. Carlos Góis, 476 AP 103</h2>
        <p>Rooms equipped with Smart TV, cable TV and Wi-Fi. And when you want to relax, you'll be happy to discover that each Tabas room comes with high-quality mattresses, luxury linens and towels. And these are just some of the amenities of this apartment.</p>
        <p><a class="btn btn-dark" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4"> 
                       
            <%= image_tag("apartments_8.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle seg-carro") %>
                
            <h2>R. Visconde de Pirajá, 22</h2>
            <p> In it you will find modern and sophisticated furniture, fully equipped kitchen with first-rate appliances, coffee machine in capsules and utensils such as crockery, bowls, pan sets, cutlery and so on.</p>
            <p><a class="btn btn-dark" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <%= image_tag("apartments_7.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle seg-carro") %>
        
        <h2>R. Redentor, 291</h2>
        <p> In it you will find modern and sophisticated furniture, fully equipped kitchen with first-rate appliances, coffee machine in capsules and utensils such as crockery, bowls, pan sets, cutlery and so on</p>
        <p><a class="btn btn-dark" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">R. Carlos Góis, 476 AP 103 - <span class="text-muted">Leblon - LB016.</span></h2>
        <p class="lead">This Tabas apartment located in Leblon - Rio de Janeiro, close to restaurants such as Olivia Saladas, Café Cardin, Mc Donald's. 110 meters from ZonaSul Supermarket, 130 meters from Bodytech, 500 meters from Leblon Beach. In it you will find modern and sophisticated furniture, fully equipped kitchen with first-rate appliances, coffee machine in capsules and utensils such as crockery, bowls, pan sets, cutlery and so on. Rooms equipped with Smart TV, cable TV and Wi-Fi. And when you want to relax, you'll be happy to discover that each Tabas room comes with high-quality mattresses, luxury linens and towels. And these are just some of the amenities of this apartment. We take care of everything so that you can simply enjoy your stay and feel at home.</p>
      </div>
      <div class="col-md-5">
        
        <%= image_tag("apartments_12.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle ter-carro") %>
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">R. Redentor, 291 - <span class="text-muted">Ipanema - IP009 </span></h2>
        <p class="lead">This Tabas apartment located in Ipanema - Rio de Janeiro, close to restaurants such as Posí Mozza & Mare, Gurumê, Esplanada Grill. 180 meters from Bodytech, 300 meters from Loja Americanas and 350 meters from ZonaSul Supermarket. In it you will find modern and sophisticated furniture, fully equipped kitchen with first-rate appliances, coffee machine in capsules and utensils such as crockery, bowls, pan sets, cutlery and so on. Rooms equipped with Smart TV, cable TV and Wi-Fi. And when you want to relax, you'll be happy to discover that each Tabas room comes with high-quality mattresses, luxury linens and towels. And these are just some of the amenities of this apartment. We take care of everything so that you can simply enjoy your stay and feel at home.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <%= image_tag("apartments_13.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle ter-carro") %>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">R. Visconde de Pirajá, 22 - <span class="text-muted">Ipanema - IP006</span></h2>
        <p class="lead">This Tabas apartment located in Ipanema - Rio de Janeiro, close to restaurants such as Zé Boteco, Copanema Mix, Osório Bar. 1 meter from HortiFruti, 100 meters from Bodytech and 140 meters from ZonaSul Supermarket. In it you will find modern and sophisticated furniture, fully equipped kitchen with first-rate appliances, coffee machine in capsules and utensils such as crockery, bowls, pan sets, cutlery and so on. Rooms equipped with Smart TV, cable TV and Wi-Fi. And when you want to relax, you'll be happy to discover that each Tabas room comes with high-quality mattresses, luxury linens and towels. And these are just some of the amenities of this apartment. We take care of everything so that you can simply enjoy your stay and feel at home.</p>
      </div>
      <div class="col-md-5">
        <%= image_tag("apartments_14.jpg", :alt => "design",class:"bd-placeholder-img rounded-circle ter-carro") %>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->

   <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2021 Tabas, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>

tabas/app/views/home/index.html.erb
    <div id="index">
        <section id="home" class="d-flex"><!-- inicio home-->
            <div class="container align-self-center"><!-- inicio container-->
            <div class="row"><!-- inicio row-->
                <div class="col-md-12 centralizar">

                    <h1 class="capa margin">Your home wherever you are</h1>
                    <h6 class="capa">Beautifully designed, fully furnished apartments in São Paulo and Rio de Janeiro to make you feel at home</h6>

                    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                        <button type="button" class="btn btn-light">Explore a place</button>

                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Search
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                            <li>
                            <%= link_to 'Rio de Janeiro', home_houses_path, class:"dropdown-item" %>
                            </li>
                            <li>
                            <%= link_to 'São Paulo', home_houses_path, class:"dropdown-item" %>
                            </li>
                            </ul>
                        </div>
                    </div>

                </div>

            
            </div><!-- fim row-->
            </div><!-- fim container-->
        </section><!-- fim home-->

        <section id="servicos" class="caixa"><!-- INICIO Servicos -->
            <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <span>PREMIUM CHOICE</span>
                    <h3>Living in a Tabas home</h3>
                    <h5> We offer fully renovated apartments at the best locations in São Paulo and Rio de Janeiro. Ease, comfort and much more.</h5>
                    
                    <div class="row cartao">
                        <div class="col-md-6 card cartao" style="width: 18rem;">
                            <%= image_tag("icon_1.png", :alt => "design",class: "rounded mx-auto d-block img") %>
                            <div class="card-body">
                                <p class="card-text">Beautiful interior design</p>
                            </div>
                        </div>
                    
                        <div class="col-md-6 card cartao" style="width: 18rem;">
                            <%= image_tag("icon_2.png", :alt => "design",class: "rounded mx-auto d-block img") %>
                            <div class="card-body">
                                <p class="card-text">Flexible renting</p>
                            </div>
                        </div>

                        <div class="col-md-6 card cartao" style="width: 18rem;">
                            <%= image_tag("icon_3.png", :alt => "design",class: "rounded mx-auto d-block img") %>
                            <div class="card-body">
                                <p class="card-text">Support service</p>
                            </div>
                        </div>

                        <div class="col-md-6 card cartao" style="width: 18rem;">
                            <%= image_tag("icon_4.png", :alt => "design",class: "rounded mx-auto d-block img") %>
                            <div class="card-body">
                                <p class="card-text">Ultra high-speed Internet</p>
                            </div>
                        </div>
                    </div>
                    


                    <a class="btn btn-dark" href="/home/houses" role="button">Rent now</a>
                </div> 
            </div>
            </div>
        </section><!-- FIM Servicos -->

        <section id="recursos"> <!--INICIO Recursos-->
            <div class="container">
            <div class="row">

                <div class="col-md-6 text-start">
                    <span>LANDLORDS</span>
                    <h3>Renting for Tabas</h3>
                    <h5>Relax and get paid. That simple. We renew, renovate, find quality tenants and all the property management. It’s you worry-free.</h5>
                    <a class="btn btn-dark" href="/home/houses" role="button">Discover more</a>
                </div>
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-6">
                            <%= image_tag("ap_3.gif", :alt => "high tech",class: "rounded mx-auto d-block gif") %>
                        </div>
                    
                    </div>
                </div>
                
        
            </div>
            
            </div>

        </section><!--FIM Recursos-->

        <footer  class="py-5">
            <div class="container">
                
                <div class="row text-start">
                        <div class="col-2">
                            <h6>CONTACT US</h6>
                            <p>Av. Nove de Julho, 5109 2º floor, Itaim Bibi, São Paulo - SP, 01407-200</p>
                            </ul>
                        </div>

                    <div class="col-2">
                        <h6>GENERAL INFO</h6>
                        <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                        </ul>
                    </div>

                    <div class="col-2">
                        <h6>FOR OWNERS</h6>
                        <p>proprietario@tabas.com.br</p>
                        <p>+55 11 4632 3312</p>
                    </div>

                    <div class="col-2">
                        <h6>FOR CORPORATE</h6>
                        <p>corporate@tabas.com.br</p>
                        <p>+55 11 4632 3312</p>
                    
                    </div>

                    
                    

                    
                </div>

                    <div class="d-flex justify-content-between py-4 my-4 border-top">
                        <p>&copy;Copyright 2021 TABAS. All rights reserved.</p> 

                        <%= image_tag("tabas.svg", :alt => "design",class: "rounded mx-auto d-block logo") %>  
                    </div>
                
            </div>

        </footer>
    </div>

  

    
  

tabas/app/views/houses/_form.html.erb
<div class="form-control">
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-text form-control" %>
  </div>

  <div class="field">
    <%= form.label :address, class:"mt-2" %>
    <%= form.text_field :address, class:"form-text form-control" %>
  </div>

  <div class="field">
    <%= form.label :prince, class:"mt-2" %>
    <%= form.number_field :prince, class:"form-text form-control" %>
  </div>

  <div class="field">
    <%= form.label :rooms, class:"mt-2" %>
    <%= form.number_field :rooms, class:"form-text form-control" %>
  </div>

  <div class="field">
    <%= form.label :bathrooms, class:"mt-2" %>
    <%= form.number_field :bathrooms, class:"form-text form-control" %>
  </div>

  <div class="field">
    <%= form.label :picture_one, class:"mt-2" %>
    <%= form.text_field :picture_one, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :picture_two, class:"mt-2" %>
    <%= form.text_field :picture_two, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :picture_three, class:"mt-2" %>
    <%= form.text_field :picture_three, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>
</div>

tabas/app/views/houses/edit.html.erb
<div class="container margin">
<h1>Editing House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Show', @house, class:"btn btn-dark mt-2" %> 
<%= link_to 'Back', houses_path, class:"btn btn-dark mt-2" %>
</div>

tabas/app/views/houses/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 class="margin">Houses</h1>

<table class="table table-dark table-striped table-hover table-bordered">
  <thead >
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Prince</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th>Picture one</th>
      <th>Picture two</th>
      <th>Picture three</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.name %></td>
        <td><%= house.address %></td>
        <td><%= house.prince %></td>
        <td><%= house.rooms %></td>
        <td><%= house.bathrooms %></td>
        <td><%= house.picture_one %></td>
        <td><%= house.picture_two %></td>
        <td><%= house.picture_three %></td>
        <td><%= link_to 'Show', house %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New House', new_house_path, class:"btn btn-dark" %>
</div>

tabas/app/views/houses/new.html.erb
<div class="container margin">
<h1>New House</h1>

<%= render 'form', house: @house %>

<%= link_to 'Back', houses_path, class:"btn btn-dark mt-2" %>
</div>

tabas/app/views/houses/show.html.erb
<div class="container table">
<p id="notice"><%= notice %></p>

  <div class="col-md-6 margin">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
        <h1>
         <p>
            <strong>Name:</strong>
            <%= @house.name %>
          </p>
        </h1> 
          <p>
            <strong>Address:</strong>
            <%= @house.address %>
          </p>

          <p>
            <strong>Prince:</strong>
            <%= @house.prince %>
          </p>

          <p>
            <strong>Rooms:</strong>
            <%= @house.rooms %>
          </p>
          
          <p>
            <strong>Bathrooms:</strong>
            <%= @house.bathrooms %>
          </p>

          <p>
            <strong>Picture one:</strong>
            <%= @house.picture_one %>
          </p>

          <p>
            <strong>Picture two:</strong>
            <%= @house.picture_two %>
          </p>

          <p>
            <strong>Picture three:</strong>
            <%= @house.picture_three %>
          </p>



          <%= link_to 'Edit', edit_house_path(@house), class:"btn btn-outline-light" %>
          <%= link_to 'Back', houses_path, class:"btn btn-outline-light" %>
        </div>
      </div>

</div>

tabas/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

    <title>Tabas</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </head>
 
  <body>

  
  <%= render 'home/header'%>

  <%= yield %>

  

  



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>